# Generated by Django 5.0.6 on 2024-10-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='burgerlist',
            options={'verbose_name_plural': 'Burger List'},
        ),
        migrations.AddField(
            model_name='burgerlist',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
