# Generated by Django 5.0.6 on 2024-10-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appburger', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
